server:
  port: 8888

dubbo:
  application:
    name: myGateway
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

spring:
  cloud:
    gateway:
      routes:
        - id: provider
          uri: lb://myProvider
          predicates:
            - Path=/api1/**
          filters:
            - RewritePath=/provider/(?<segment>.*),/$\{segment}

        - id: consumer
          uri: lb://myConsumer
          predicates:
            - Path=/api2/**
          filters:
            - RewritePath=/consumer/(?<segment>.*),/$\{segment}
